# Generated by Django 4.2.2 on 2023-09-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicinalMarijuana', '0002_strains_delete_uploadstraintodb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strains',
        ),
    ]
