# Generated by Django 4.2.4 on 2023-11-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinalMarijuana', '0005_sliders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('btn', models.CharField(max_length=100)),
                ('image', models.ImageField(default='profile.png', upload_to='homepage')),
            ],
        ),
    ]
